name: Maven Publish

on:
  push:
    branches: [ 'release' ]
  workflow_dispatch:
    inputs:
      revision:
        description: 'The version to release'
        required: true
        default: '0.0.1-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.revision }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: maven

      - name: Publish package
        run: |
          mvn -B -ntp -U deploy -Prelease -Drevision=${{ inputs.revision }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}