name: Maven Build

on:
  push:
    branches: [ "main" , 'dev' ]
  pull_request:
    branches: [ "main" , 'dev' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' , '17' , '21' , '25' ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B -U -ntp test -Ptest,coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rosestack/rose-spring
